# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
block_timestamp = 1_680_220_800                                    # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "paris"                                              # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.24"
src = "src"
test = "test"
fs_permissions = [{ access = "read", path = "deployConfig.json" }]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
arbitrum = { key = "${API_KEY_ARBISCAN}" }
arbitrum_sepolia = { key = "${API_KEY_ARBISCAN}" }
bsc = { key = "${API_KEY_BSCSCAN}" }
bsc_testnet = { key = "${API_KEY_BSCSCAN}" }
polygon = { key = "${API_KEY_POLYGONSCAN}" }
polygon_mumbai = { key = "${API_KEY_POLYGONSCAN}" }
linea = { key = "${API_KEY_LINEASCAN}" }
linea_goerli = { key = "${API_KEY_LINEASCAN}" }
base = { key = "${API_KEY_BASESCAN}" }
base_sepolia = { key = "${API_KEY_BASESCAN}" }
core = { chain = 1116, url = "https://scan.coredao.org/api", key = "${API_KEY_CORESCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
localhost = "http://localhost:8545"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
arbitrum_sepolia = "https://arbitrum-sepolia.infura.io/v3/${API_KEY_INFURA}"
bsc = "https://bsc-dataseed.binance.org"
bsc_testnet = "https://bsc-testnet.public.blastapi.io"
polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
polygon_mumbai = "https://polygon-mumbai.infura.io/v3/${API_KEY_INFURA}"
linea = "https://linea-mainnet.infura.io/v3/${API_KEY_INFURA}"
linea_goerli = "https://linea-goerli.infura.io/v3/${API_KEY_INFURA}"
base_sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"
degen = "https://rpc.degen.tips"
lightlink = "https://replicator.phoenix.lightlink.io/rpc/v1	"
blast = "https://blast.blockpi.network/v1/rpc/public"
areon = "https://mainnet-rpc.areon.network"
core = "https://rpc.coredao.org"
